[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable Netlify form handling
[context.production]
  environment = { NODE_ENV = "production" } 